//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewToDoApp.Models
{
    using System;
    using System.Collections.Generic;


    public partial class ListDetail
    {
       
        public int LID { get; set; }
        public string title { get; set; }
        public string date { get; set; }
        public string status { get; set; }
        public string delmode { get; set; }
    }
}
